name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1.101.0
      with:
        ruby-version: 2.6.8
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 2 --retry 1
        bundle exec rake
  
  build_2_7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1.101.0
      with:
        ruby-version: 2.7.4
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 2 --retry 1
        bundle exec rake
        
  build_3_0:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1.101.0
      with:
        ruby-version: 3.0.2
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 2 --retry 1
        bundle exec rake
